
cache:
  paths:
    - target/
    - .cargo/

image: "rust:latest"


default:
  before_script:
    - rustc --version 
    - cargo --version
    - apt-get update -yqq
    - apt-get install -yqq --no-install-recommends build-essential libspeechd-dev xorg-dev libgtk-3-dev cmake

stages:
  - build

build-code:
  stage: build
  script:
    - rustup component add rustfmt
    - cargo fmt -- --check
    - rustup component add clippy
    - cargo clippy --workspace --all-targets --all-features --  -D warnings -W clippy::all
    - cargo test --workspace
    - cargo build --workspace --release