variables:
  CARGO_HOME: $CI_PROJECT_DIR/.cargo
# cannot add Cargo deny yet because of some dependencies still being "git" like wgpu and its friends.
cache:
  paths:
    - target/
    - .cargo/

image: "rust:latest"


default:
  before_script:
    - rustc --version 
    - cargo --version
    - apt-get update -yqq
    - apt-get install -yqq --no-install-recommends build-essential libspeechd-dev xorg-dev libgtk-3-dev cmake libasound2-dev libudev-dev
  after_script:
    - echo "size of $CARGO_HOME"
    - du -sh $CARGO_HOME
    - echo "size of target"
    - du -sh target

stages:
  - build

build-code:
  stage: build
  script:
    - rustup component add rustfmt
    - cargo fmt --all -- --check
    - rustup component add clippy
    - cargo clippy --workspace --all-targets --all-features --  -D warnings -W clippy::all
    - cargo test --workspace --all-targets --all-features
    - cargo build --workspace --all-targets