[package]
name = "jokolay"
version = "0.1.12"
description = "An Overlay for Guild Wars 2 in rust"
license = "MIT"
authors = ["coderedart <redartofcode@gmail.com>"]
edition = "2018"
keywords = ["GuildWars2", "GW2", "Overlay"]

[dependencies]
#glfw = { version = "0.41.0", git = "https://github.com/coderedart/glfw-rs.git" }
#glow = { version = "0.10.0", git = "https://github.com/coderedart/glow.git" }
glfw = {version =  "*", path = "../glfw-rs"}
glow = {version =  "*", path = "../glow"}
# jokolink = {version  = "*", path =  "../jokolink"}
jokolink = "0.2.5"
vfs = "0.5"
quick-xml = { version = "0.22", features = ["serialize"] }
#serde-xml-rs = "0.5.0"
serde = { version = "1", features = ["derive"] }
serde_path_to_error = "0.1"
serde_derive = "1"
serde_repr = "0.1"
hex = { version = "0.4", features = ["serde"] }
base64 = "0.13"
uuid = { version = "0.8", features = ["serde", "v4"] }
num-derive = "0.3"
num-traits = "0.2"
bytemuck = "1"
egui = {version = "0.14", default-features = false, features = ["persistence", "multi_threaded", "default_fonts"]}
glm = { version = "0.15", package = "nalgebra-glm" }
image = { version = "0.23", default-features = false, features = ["png"] }
device_query = "0.2"
#copypasta = "0.7.1"
log = "0.4"
simplelog = "0.10"
fastrand = "1"
anyhow = "1"
rayon = "1"
bus = "2"
guillotiere = "0.6"
raw-window-handle = "0.3"
serde_json = "1"
zip-extensions = "0.6"
zip = "0.5"
tempfile = "3.2.0"
git2 = "0.13"
rfd = "0.5"
open = "2"

[target.'cfg(unix)'.dependencies]
x11rb = {version =  "0.9", features = ["all-extensions"]}
psutil = "3"

[profile.release]
incremental = true
