
[profile.dev.package."*"]
opt-level = 3

[profile.dev]
opt-level = 1

[profile.release]
# lto = true
# codegen-units = 1

[workspace]
resolver = "2"
members = [
    "crates/jokolink",
    "crates/jmf",
    "crates/jokoapi",
    "crates/joko_plugins",
    "crates/bevy_glfw",
    "crates/jokolay_desktop",
    "crates/jokolay_web",
]
