[package]
name = "jokolay"
version = "0.1.0"
authors = ["coderedart <redartofcode@gmail.com>"]
edition = "2018"

[dependencies]
bytemuck = "1.5.1"
glow = "0.9.0"
cgmath = "0.18.0"

[dependencies.glfw]
git = "https://github.com/coderedart/glfw-rs"
