[package]
name = "jokolay"
version = "0.1.0"
description = "An Overlay for Guild Wars 2 in rust"
license = "MIT"
authors = ["coderedart <redartofcode@gmail.com>"]
edition = "2018"
keywords = ["GuildWars2", "GW2", "Overlay"]

[dependencies]
bytemuck = "1.5.1"
glow = "0.9.0"
cgmath = "0.18.0"
glfw = "0.41.0"

[patch.crates-io]
glfw = {git = "https://github.com/coderedart/glfw-rs" }
