[package]
name = "jokolay"
version = "0.1.10"
description = "An Overlay for Guild Wars 2 in rust"
license = "MIT"
authors = ["coderedart <redartofcode@gmail.com>"]
edition = "2018"
keywords = ["GuildWars2", "GW2", "Overlay"]

[dependencies]
bytemuck = "1.5.1"
glow = "0.10.0"
jokoapi = "0.1.1"
jokolink = "0.1.23"
num-derive = "0.3.3"
num-traits = "0.2.14"
serde = {version = "1.0.126", features = ["derive"]}
serde_derive = "1.0.126"
serde_repr = "0.1.7"
quick-xml = { version = "0.22.0", features = ["serialize"]}
nalgebra-glm = "0.13.0"
image = "0.23.14"
anyhow = "1.0.41"
egui = "0.13.0"
epi = "0.13.0"
device_query = "0.2.8"
copypasta = "0.7.1"
parking_lot = "0.11.1"
winit = "0.25.0"
imgui-opengl-renderer = "0.11.0"
imgui = "0.7.0"
#glfw = "0.41.0"

[dependencies.glfw]
version = "0.41.0"
git = "https://github.com/coderedart/glfw-rs.git"

#[patch.crates-io]
#glfw = {git = "https://github.com/coderedart/glfw-rs.git" }

#[target.'cfg(windows)'.dependencies]
#jokolink = "0.1.23"
