[package]
name = "jokolay"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# mumblelink
jokolink = { path = "crates/jokolink" }
jokoapi = { path = "crates/jokoapi" }
jmf = { path = "crates/jmf" }
egui_overlay = { version = "0.2" }

[profile.dev.package."*"]
opt-level = 3

[profile.dev]
opt-level = 1

[profile.release]
# lto = true
# codegen-units = 1

[workspace]
resolver = "2"
members = ["crates/jokolink", "crates/jmf", "crates/jokoapi"]
