[package]
name = "jokolay"
version = "0.1.2"
description = "An Overlay for Guild Wars 2 in rust"
license = "MIT"
authors = ["coderedart <redartofcode@gmail.com>"]
edition = "2018"
keywords = ["GuildWars2", "GW2", "Overlay"]

[dependencies]
bytemuck = "1.5.1"
glow = "0.10.0"
cgmath = "0.18.0"
glfw = "0.41.0"
jokoapi = "0.1.0"
jokolink = "0.1.2"
num-derive = "0.3.3"
num-traits = "0.2.14"

[patch.crates-io]
glfw = {git = "https://github.com/coderedart/glfw-rs" }

[target.'cfg(windows)'.dependencies]
jokolink = "0.1.2"
