[package]
name = "jokolay"                                  # ToDo
version = "0.1.0"
publish = false
authors = ["Red Artist <redartofcode@gmail.com>"]
edition = "2021"
license = "MIT OR Apache-2.0"

[profile.dev.package."*"]
opt-level = 3

[profile.dev]
opt-level = 1

[profile.release]
lto = true
codegen-units = 1

[workspace]
resolver = "2"
members = [
    #    "crates/jokolink",
    "crates/jmf",
    #    "crates/jokoapi",
    "crates/bevy_glfw",
]


[features]
default = [
    "bevy/bevy_winit",
    "bevy/render",
    "bevy/png",
    "bevy/x11",
    "bevy_kira_audio/ogg",
]

dev = ["bevy/dynamic"]

[dependencies]
bevy = { version = "0.7", default-features = false }
bevy_kira_audio = { version = "0.9" }
bevy_asset_loader = { version = "0.10" }
rand = "0.8.3"
# until bevy_egui merges the PR to remove bevy_winit dependency.
bevy_egui = { version = "0.14.0", git = "https://github.com/coderedart/bevy_egui.git" }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
bevy_glfw = { version = "*", path = "crates/bevy_glfw" }

[build-dependencies]
embed-resource = "1.4"
