[advisories]
db-path = "~/.cargo/advisory-db"
db-urls = ["https://github.com/rustsec/advisory-db"]
vulnerability = "deny"
unmaintained = "deny"
yanked = "deny"
notice = "deny"


[licenses]
unlicensed = "deny"
copyleft = "deny"
allow = [
    "MIT",
    "Apache-2.0",
    "BSD-3-Clause",
    "ISC",
    "Zlib",
    "0BSD",
    "BSD-2-Clause",
    "CC0-1.0",
    "BSL-1.0"
]
default = "deny"


[bans]
multiple-versions = "deny"
wildcards = "deny"
highlight = "all"


[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = [
    "https://github.com/gfx-rs/wgpu",
    "https://github.com/gfx-rs/naga",
    "https://github.com/gfx-rs/metal-rs",
    "https://github.com/gfx-rs/d3d12-rs",
    "https://github.com/coderedart/glfw-rs",
    "https://github.com/coderedart/glfw-sys",
    "https://github.com/ostrosco/device_query",
    "https://github.com/emilk/egui.git"
]