name: jokolink
version: "0.1"
about: copies MumbleLink info to z:/dev/shm so that linux processes can read it.
author: Red Artist <redartofcode@gmail.com>



# All Args must be defined in the 'args:' list where the name of the arg, is the
# key to a Hash object
args:
    - termlog:
        short: t
        help: max logging level to terminal stdout/stderr
        possible_values: [error, warn, info, debug, trace]
        takes_value: true
    
    - filelog:
        short: l
        help: max logging level to logfile
        possible_values: [error, warn, info, debug, trace]
        takes_value: true
    
    - logfile:
        short: f
        help: the filepath to logfile.
        takes_value: true

    - mumble:
        short: m
        help: the mumble link name that gw2 uses
        takes_value: true

    - interval:
        short: i
        help: how often jokolink copies mumble data to /dev/shm in milliseconds
        takes_value: true

    - gwcheck:
        short: g
        help: how often jokolink checks if gw2 is alive (and quits if gw2 is not alive) in seconds
        takes_value: true
    

