[build]
jobs = 6
target = "x86_64-pc-windows-gnu"
# we could probably add more features like sse4 later
[target.x86_64-pc-windows-gnu]
rustflags = ["-C", "target-feature=+crt-static"]
linker = "x86_64-w64-mingw32-gcc"
ar = "x86_64-w64-mingw32-gcc-ar"
