[package]
name = "jokolink"
description = "A crate to copy MumbleLink of Guild Wars 2 by running in wine and copying it to linux filesystem for native access by linux apps"
license = "MIT"
repository = "https://github.com/coderedart/jokolink.git"
version = "0.4.0"
authors = ["coderedart <redartofcode@gmail.com>"]
edition = "2021"

[features]


[dependencies]
thiserror = { version = "1", default-features = false }
color-eyre = { version = "0.6", default-features = false }
# tracing-error = { version = "*", default-features = false }
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1", default-features = false, features = ["std"] }
widestring = { version = "1", default-features = false, features = ["std"] }
bitflags = { version = "1", default-features = false }
num-derive = { version = "0", default-features = false }
num-traits = { version = "0", default-features = false }
tracing-appender = { version = "0" }
tracing-subscriber = { version = "0" }
tracing = { version = "0", default-features = false }
sysinfo = { version = "0.25.1", default-features = false, features = [] }

[target.'cfg(unix)'.dependencies]
x11rb = { version = "0.10.1", default-features = false, features = [] }

[target.'cfg(windows)'.dependencies]
windows = { version = "0.38.0", features = [
    "Win32_System_Memory",
    "Win32_Foundation",
    "Win32_Security",
    "Win32_UI_WindowsAndMessaging",
    "Win32_System_Threading",
] }
